version: '3.8'

services:
  valtrex-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valtrex-tienda
    ports:
      - "3000:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - valtrex-network

networks:
  valtrex-network:
    driver: bridge
