version: '3.8'

services:
  urbanstyle-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urbanstyle-tienda
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - urbanstyle-network

networks:
  urbanstyle-network:
    driver: bridge
